import 'dart:async';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter/services.dart';

/// Metadata for one architecture-specific APK delta.
///
/// A delta is not itself installable. Applying it to the exact base APK must
/// produce the signed target APK byte-for-byte.
class AndroidDeltaPackage {
  final String fromVersion;
  final String fromSha256;
  final String toVersion;
  final String toSha256;
  final String patchUrl;
  final int patchSize;

  const AndroidDeltaPackage({
    required this.fromVersion,
    required this.fromSha256,
    required this.toVersion,
    required this.toSha256,
    required this.patchUrl,
    this.patchSize = 0,
  });

  factory AndroidDeltaPackage.fromJson(Map<String, dynamic> json) {
    return AndroidDeltaPackage(
      fromVersion: json['from_version']?.toString() ?? '',
      fromSha256: json['from_sha256']?.toString().toLowerCase() ?? '',
      toVersion: json['to_version']?.toString() ?? '',
      toSha256: json['to_sha256']?.toString().toLowerCase() ?? '',
      patchUrl: json['patch_url']?.toString() ?? '',
      patchSize: int.tryParse(json['patch_size']?.toString() ?? '') ?? 0,
    );
  }

  bool get isUsable =>
      fromVersion.isNotEmpty &&
      fromSha256.length == 64 &&
      toVersion.isNotEmpty &&
      toSha256.length == 64 &&
      patchUrl.isNotEmpty;
}

/// Applies the small CDTDELTA1 format generated by scripts/android_delta.py.
class AndroidDeltaService {
  static const MethodChannel _channel = MethodChannel(
    'com.math_quiz.junpgle.com.math_quiz_app/app_update',
  );

  static const List<int> _magic = <int>[
    0x43, // C
    0x44, // D
    0x54, // T
    0x44, // D
    0x45, // E
    0x4c, // L
    0x54, // T
    0x41, // A
  ];
  static const int _formatVersion = 1;
  static const int _copyOperation = 0;
  static const int _dataOperation = 1;
  static const int _maxOperationCount = 1000000;
  static const int _maxDataOperationSize = 16 * 1024 * 1024;

  static Future<String?> getInstalledApkPath() async {
    try {
      return await _channel.invokeMethod<String>('getInstalledApkPath');
    } on MissingPluginException {
      return null;
    } on PlatformException {
      return null;
    }
  }

  static Future<String> sha256Of(File file) async {
    final digest = await sha256.bind(file.openRead()).first;
    return digest.toString();
  }

  static Future<bool> matchesSha256(File file, String expected) async {
    if (!await file.exists() || expected.trim().length != 64) return false;
    final actual = await sha256Of(file);
    return actual.toLowerCase() == expected.trim().toLowerCase();
  }

  /// Applies a delta to [baseApk], writing the result to [outputApk].
  ///
  /// The output is deleted when parsing, copying, or target verification
  /// fails, so callers can safely fall back to the full APK.
  static Future<File> applyPatch({
    required File baseApk,
    required File patchFile,
    required File outputApk,
    String? expectedBaseSha256,
    String? expectedTargetSha256,
  }) async {
    if (!await baseApk.exists()) {
      throw const FileSystemException('Base APK does not exist');
    }
    if (!await patchFile.exists()) {
      throw const FileSystemException('Delta patch does not exist');
    }

    if (expectedBaseSha256 != null && expectedBaseSha256.isNotEmpty) {
      final matches = await matchesSha256(baseApk, expectedBaseSha256);
      if (!matches) {
        throw const FormatException('Base APK SHA-256 does not match');
      }
    }

    final base = await baseApk.open();
    final patch = await patchFile.open();
    final sink = outputApk.openWrite();
    var sinkClosed = false;
    var baseClosed = false;
    var patchClosed = false;

    try {
      final header = await patch.read(8);
      if (!_bytesEqual(header, _magic)) {
        throw const FormatException('Invalid CDT delta magic');
      }

      final formatVersion = await _readUint32(patch);
      if (formatVersion != _formatVersion) {
        throw FormatException('Unsupported CDT delta version: $formatVersion');
      }

      final baseSize = await _readUint64(patch);
      final targetSize = await _readUint64(patch);
      final chunkSize = await _readUint32(patch);
      final operationCount = await _readUint32(patch);

      if (baseSize != await baseApk.length()) {
        throw const FormatException('Base APK size does not match');
      }
      if (chunkSize == 0 || chunkSize > 16 * 1024 * 1024) {
        throw const FormatException('Invalid delta chunk size');
      }
      if (operationCount > _maxOperationCount) {
        throw const FormatException('Too many delta operations');
      }

      var outputSize = 0;
      for (var index = 0; index < operationCount; index++) {
        final operation = await patch.read(1);
        if (operation.length != 1) {
          throw const FormatException('Unexpected end of delta operation');
        }

        final type = operation[0];
        final offset = await _readUint64(patch);
        final length = await _readUint32(patch);
        if (length == 0) {
          throw const FormatException('Zero-length delta operation');
        }
        if (outputSize > targetSize - length) {
          throw const FormatException('Delta output exceeds target size');
        }

        if (type == _copyOperation) {
          if (offset > baseSize || length > baseSize - offset) {
            throw const FormatException('Delta copy range exceeds base APK');
          }
          await base.setPosition(offset);
          await _copyBaseBytes(base, sink, length);
        } else if (type == _dataOperation) {
          if (length > _maxDataOperationSize) {
            throw const FormatException('Delta data operation is too large');
          }
          await _copyPatchBytes(patch, sink, length);
        } else {
          throw FormatException('Unknown delta operation type: $type');
        }

        outputSize += length;
        if (index % 32 == 0) await sink.flush();
      }

      if (outputSize != targetSize) {
        throw FormatException(
          'Delta output size mismatch: $outputSize != $targetSize',
        );
      }

      await sink.flush();
      await sink.close();
      sinkClosed = true;
      await base.close();
      baseClosed = true;
      await patch.close();
      patchClosed = true;

      if (expectedTargetSha256 != null && expectedTargetSha256.isNotEmpty) {
        final matches = await matchesSha256(outputApk, expectedTargetSha256);
        if (!matches) {
          throw const FormatException('Target APK SHA-256 does not match');
        }
      }
      return outputApk;
    } catch (_) {
      if (!sinkClosed) await sink.close();
      if (!baseClosed) await base.close();
      if (!patchClosed) await patch.close();
      if (await outputApk.exists()) await outputApk.delete();
      rethrow;
    }
  }

  static Future<void> _copyBaseBytes(
    RandomAccessFile base,
    IOSink sink,
    int length,
  ) async {
    var remaining = length;
    while (remaining > 0) {
      final bytes =
          await base.read(remaining > 64 * 1024 ? 64 * 1024 : remaining);
      if (bytes.isEmpty) {
        throw const FormatException('Unexpected end of base APK');
      }
      sink.add(bytes);
      remaining -= bytes.length;
    }
  }

  static Future<void> _copyPatchBytes(
    RandomAccessFile patch,
    IOSink sink,
    int length,
  ) async {
    var remaining = length;
    while (remaining > 0) {
      final bytes =
          await patch.read(remaining > 64 * 1024 ? 64 * 1024 : remaining);
      if (bytes.isEmpty) {
        throw const FormatException('Unexpected end of delta data');
      }
      sink.add(bytes);
      remaining -= bytes.length;
    }
  }

  static Future<int> _readUint32(RandomAccessFile file) async {
    final bytes = await file.read(4);
    if (bytes.length != 4) throw const FormatException('Unexpected delta EOF');
    return bytes[0] | (bytes[1] << 8) | (bytes[2] << 16) | (bytes[3] << 24);
  }

  static Future<int> _readUint64(RandomAccessFile file) async {
    final bytes = await file.read(8);
    if (bytes.length != 8) throw const FormatException('Unexpected delta EOF');
    var value = 0;
    for (var index = 0; index < 8; index++) {
      value |= bytes[index] << (index * 8);
    }
    return value;
  }

  static bool _bytesEqual(List<int> left, List<int> right) {
    if (left.length != right.length) return false;
    for (var index = 0; index < left.length; index++) {
      if (left[index] != right[index]) return false;
    }
    return true;
  }
}
