INSERT OR REPLACE INTO app_name_mappings (package_name, mapped_name, category) VALUES
-- 社交通讯类
('com.tencent.mm', '微信', '社交通讯'),
('Weixin', '微信', '社交通讯'),
('com.tencent.mobileqq', 'QQ', '社交通讯'),
('QQ', 'QQ', '社交通讯'),
('com.ss.android.ugc.aweme', '抖音', '影音娱乐'),
('抖音', '抖音', '影音娱乐'),
('微博', '微博', '社交通讯'),
('小红书', '小红书', '社交通讯'),
('百度贴吧', '百度贴吧', '社交通讯'),
('钉钉', '钉钉', '社交通讯'),
('DingTalk', '钉钉', '社交通讯'),
('腾讯会议', '腾讯会议', '社交通讯'),
('短信', '短信', '社交通讯'),
('WeChatAppEx', '微信小程序', '社交通讯'),
('全民K歌', '全民K歌', '影音娱乐'),

-- 影音娱乐类
('tv.danmaku.bili', '哔哩哔哩', '影音娱乐'),
('tv.danmaku.bilibilihd', '哔哩哔哩HD', '影音娱乐'),
('网易云音乐', '网易云音乐', '影音娱乐'),
('猫眼', '猫眼', '影音娱乐'),
('大麦', '大麦', '影音娱乐'),
('cn.com.livelab', '纷玩岛', '影音娱乐'),
('com.bide.haoyoukan.buhaokan.kanbukan.dj.ss', '特狗', '影音娱乐'),
('PotPlayer', 'PotPlayer', '影音娱乐'),
('P站助手Lite', 'P站助手', '影音娱乐'),

-- 购物支付类
('com.taobao.taobao', '淘宝', '购物支付'),
('com.eg.android.AlipayGphone', '支付宝', '购物支付'),
('com.xunmeng.pinduoduo', '拼多多', '购物支付'),
('com.jingdong.app.mall', '京东', '购物支付'),
('识货', '识货', '购物支付'),
('com.world.compet', '识货', '购物支付'),
('中国建设银行', '建设银行', '购物支付'),
('com.unionpay', '银联', '购物支付'),
('com.xiaomi.shop', '小米商城', '购物支付'),
('大疆商城', '大疆商城', '购物支付'),

-- 游戏与辅助类
('YuanShen', '原神', '游戏与辅助'),
('原神', '原神', '游戏与辅助'),
('米游社', '米游社', '游戏与辅助'),
('米哈游启动器', '米哈游启动器', '游戏与辅助'),
('BetterGI', 'BetterGI', '游戏与辅助'),
('steam', 'Steam', '游戏与辅助'),
('小黑盒', '小黑盒', '游戏与辅助'),

-- 导航出行类
('高德地图', '高德地图', '导航出行'),
('铁路12306', '铁路12306', '导航出行'),
('智行火车票', '智行火车票', '导航出行'),
('哈啰', '哈啰', '导航出行'),
('me.ele', '美团', '生活服务'),
('美团', '美团', '生活服务'),
('美团外卖', '美团外卖', '生活服务'),

-- 健康运动类
('com.mi.health', '运动健康', '健康运动'),
('com.mi.healthresearch', '健康研究', '健康运动'),
('com.yunzhi.tiyu', '体育应用', '健康运动'),

-- 学习办公类
('com.jideos.jnotes', '云记', '学习办公'),
('云记', '云记', '学习办公'),
('com.huawei.hinote', '华为笔记', '学习办公'),
('com.chaoxing.mobile', '学习通', '学习办公'),
('com.netease.edu.ucmooc', '中国大学MOOC', '学习办公'),
('com.hfut.schedule', '聚在工大', '学习办公'),
('今日校园', '今日校园', '学习办公'),
('畅课', '畅课', '学习办公'),
('时光序', '时光序', '学习办公'),
('千问', '千问', '学习办公'),
('Qianwen', '千问', '学习办公'),
('豆包', '豆包', '学习办公'),
('Doubao', '豆包', '学习办公'),
('CountDownTodo', 'CountDownTodo', '学习办公'),
('MathQuizLite', 'CountDownTodo', '学习办公'),
('math_quiz_app', 'CountDownTodo', '学习办公'),
('效率 & 数学', 'CountDownTodo', '学习办公'),
('WPS Office', 'WPS Office', '学习办公'),
('Microsoft Word', 'Word', '学习办公'),
('WINWORD', 'Word', '学习办公'),
('Microsoft Excel', 'Excel', '学习办公'),
('EXCEL', 'Excel', '学习办公'),
('Microsoft PowerPoint', 'PowerPoint', '学习办公'),
('POWERPNT', 'PowerPoint', '学习办公'),
('网易有道词典', '有道词典', '学习办公'),
('com.duolingo', '多邻国', '学习办公'),
('cn.unipus.cloud', '外研随身学', '学习办公'),

-- 实用工具类
('com.miui.gallery', '相册', '实用工具'),
('相册', '相册', '实用工具'),
('com.miui.calculator', '计算器', '实用工具'),
('计算器', '计算器', '实用工具'),
('com.miui.weather2', '天气', '实用工具'),
('天气', '天气', '实用工具'),
('com.android.deskclock', '时钟', '实用工具'),
('时钟', '时钟', '实用工具'),
('日历', '日历', '实用工具'),
('相机', '相机', '实用工具'),
('笔记', '笔记', '学习办公'),
('浏览器', '浏览器', '实用工具'),
('Edge', 'Edge浏览器', '实用工具'),
('msedge', 'Edge浏览器', '实用工具'),
('Microsoft Edge', 'Edge浏览器', '实用工具'),
('chrome', 'Chrome浏览器', '实用工具'),
('夸克', '夸克浏览器', '实用工具'),
('com.coolapk.market', '酷安', '实用工具'),
('bin.mt.plus', 'MT管理器', '实用工具'),
('com.mt.pronto', '大狗记', '实用工具'),
('com.iflytek.oshall.ahzwfw', '皖事通', '实用工具'),
('Shizuku', 'Shizuku', '实用工具'),
('360压缩', '360压缩', '实用工具'),
('360zip', '360压缩', '实用工具'),
('7-Zip File Manager', '7-Zip', '实用工具'),
('7zFM', '7-Zip', '实用工具'),
('截图工具', '截图工具', '实用工具'),
('SnippingTool', '截图工具', '实用工具'),
('SnippingTool.exe', '截图工具', '实用工具'),
('ScreenClippingHost', '截图工具', '实用工具'),
('记事本', '记事本', '实用工具'),
('Notepad', '记事本', '实用工具'),
('Notepad.exe', '记事本', '实用工具'),
('画图', '画图', '实用工具'),
('mspaint.exe', '画图', '实用工具'),
('PcClipboard', '剪贴板工具', '实用工具'),
('Everything', 'Everything', '实用工具'),
('IDM', 'IDM', '实用工具'),
('IDMan', 'IDM', '实用工具'),
('ToDesk', 'ToDesk', '实用工具'),
('v2rayN', 'v2rayN', '实用工具'),
('Clash Verge', '代理工具', '实用工具'),
('clash-verge', '代理工具', '实用工具'),
('GHelper', 'GHelper', '实用工具'),
('搞机助手', '搞机助手', '实用工具'),
('看图', '看图', '实用工具'),
('360压缩 PDF查看器', 'PDF查看器', '实用工具'),
('123pan', '123云盘', '实用工具'),
('123云盘', '123云盘', '实用工具'),
('Nutstore Client', '坚果云', '实用工具'),
('压缩升级模块', '压缩工具', '实用工具'),
('功能解锁', '功能解锁', '实用工具'),
('Unlock_advanced_features', '功能解锁', '实用工具'),
('com.greenpoint.android.mc10086.activity', '移动10086', '实用工具'),
('com.sinovatech.unicom.ui', '联通APP', '实用工具'),
('皖事通', '皖事通', '实用工具'),
('酷安', '酷安', '实用工具'),
('MT管理器', 'MT管理器', '实用工具'),
('大狗记', '大狗记', '实用工具'),
('蜂窝 pro', '蜂窝Pro', '实用工具'),
('多多工具', '多多工具', '实用工具'),
('com.duorong.smarttool', '多多工具', '实用工具'),
('远程控制', '远程控制', '实用工具'),
('com.duokan.phone.remotecontroller', '远程控制', '实用工具'),

-- 系统应用类
('系统桌面', '系统桌面', '系统应用'),
('系统更新', '系统更新', '系统应用'),
('设置', '设置', '系统应用'),
('小米设置', '设置', '系统应用'),
('应用商店', '应用商店', '系统应用'),
('应用包管理组件', '包管理组件', '系统应用'),
('安全服务', '安全服务', '系统应用'),
('超级小爱', '超级小爱', '系统应用'),
('小艺', '小艺', '系统应用'),
('智能助理', '智能助理', '系统应用'),
('智能应用助手', '智能助手', '实用工具'),
('文件管理', '文件管理', '系统应用'),
('Windows 资源管理器', '资源管理器', '系统应用'),
('explorer', '资源管理器', '系统应用'),
('资源管理器', '资源管理器', '系统应用'),
('CredentialUIBroker', '凭据管理器', '系统应用'),
('Credential Manager UI Host', '凭据管理器', '系统应用'),
('rundll32', 'Windows主进程', '系统应用'),
('msiexec', 'Windows安装程序', '系统应用'),
('IntentResolver', '系统分享', '系统应用'),
('PickerHost', '文件选择器', '系统应用'),
('Lenovo Legion Toolkit', '拯救者工具', '系统应用'),
('小米电脑管家', '电脑管家', '实用工具'),
('XiaomiPcManager', '电脑管家', '实用工具'),
('联想电脑管家', '联想电脑管家', '实用工具'),
('LenovoPcManager', '联想电脑管家', '实用工具'),
('跨屏协作服务', '跨屏协作', '系统应用'),
('跨屏协作', '跨屏协作', '系统应用'),
('无线副屏', '无线副屏', '系统应用'),
('多屏互动', '多屏互动', '系统应用'),
('设备互联', '设备互联', '系统应用'),
('小米云服务', '小米云服务', '系统应用'),
('com.xiaomi.vipaccount', '小米账号', '系统应用'),
('小米智慧生活', '米家', '实用工具'),
('com.xiaomi.smarthome', '米家', '实用工具'),
('系统界面组件', '系统界面', '系统应用'),
('自动调节', '自动调节', '系统应用'),
('Windows 问题报告', '问题报告', '系统应用'),
('WerFault', '错误报告', '系统应用'),
('Windows 命令处理程序', 'CMD', '系统应用'),
('Windows Terminal Host', 'Windows Terminal', '系统应用'),
('Windows PowerShell', 'PowerShell', '系统应用'),
('安装卸载', '安装卸载', '系统应用'),
('Setup/Uninstall', '安装卸载', '系统应用'),
('Microsoft Office Click-to-Run Client', 'Office即点即用', '系统应用'),
('Microsoft Visual C++ 2015-2022 Redistributable (x64)', 'VC++运行库', '系统应用'),
('Microsoft Windows Desktop Runtime - 8.0.7 (x64)', '.NET运行库', '系统应用'),
('Microsoft ® Windows Based Script Host', '脚本宿主', '系统应用'),
('Reboot', '重启工具', '系统应用'),
('小米电脑管家安装程序', '电脑管家安装', '系统应用'),
('RadeonSoftware', '显卡驱动', '系统应用'),
('Adobe Installer', 'Adobe安装器', '系统应用'),
('ASUS Hotplug Controller', '华硕热插拔', '系统应用'),
('TrueUpdate Client', '自动更新工具', '系统应用'),

-- 编程类
('Android Studio', 'Android Studio', '编程'),
('studio64', 'Android Studio', '编程'),
('CLion', 'CLion', '编程'),
('clion64', 'CLion', '编程'),
('PyCharm', 'PyCharm', '编程'),
('pycharm64', 'PyCharm', '编程'),
('Visual Studio Code', 'VS Code', '编程'),
('Code.exe', 'VS Code', '编程'),
('Qt Creator', 'Qt Creator', '编程'),
('WebStorm', 'WebStorm', '编程'),
('Webstorm', 'WebStorm', '编程'),
('DB Browser for SQLite', 'SQLite浏览器', '编程'),
('DB Browser for SQLCipher', 'SQLCipher浏览器', '编程'),
('dbgview64', 'DebugView', '编程'),
('DebugView', 'DebugView', '编程'),
('Compil32', 'Inno Setup编译器', '编程'),
('VMware Workstation', 'VMware', '编程'),
('Xshell', 'Xshell', '编程'),
('Xftp', 'Xftp', '编程'),
('合并代码', '代码合并工具', '编程'),
('软著源代码生成工具', '软著工具', '编程'),
('com.github.android', 'GitHub', '编程'),
('Db.App', '数据库工具', '编程'),

-- 安全服务类
('火绒安全软件升级程序', '火绒安全', '安全服务'),
('火绒安全软件', '火绒安全', '安全服务'),
('火绒安全软件托盘程序', '火绒安全', '安全服务'),
('HipsTray', '火绒托盘', '安全服务'),
('360安全卫士', '360安全卫士', '安全服务'),
('360安全卫士 主程序模块', '360安全卫士', '安全服务'),
('360安全防护中心模块', '360安全卫士', '安全服务'),:
('360文件粉碎机', '360安全卫士', '安全服务'),
('360清理Pro', '360安全卫士', '安全服务'),
('安全卫士 系统修复模块', '360安全卫士', '安全服务'),

-- 其他类
('com.szzc', '神州租车', '实用工具'),
('Antigravity', 'Antigravity', '编程'),
('com.larus.nova', '豆包', '学习办公'),
('StarIsLand', 'StarIsLand', '实用工具'),
('com.stardawntech.starisland', 'StarIsLand', '实用工具');